package threadsConcept;

public class Registerusertest
{

	public static void main(String[] args) throws InterruptedException 
	{
		RegisterUser ur=new RegisterUser();
		Thread thread1=new Thread(ur);
		Thread thread2=new Thread(ur);
		thread1.start();
		Thread.sleep(2000);
		thread2.start();

		

	}
	
	//first thread was started and it started execution of createuser() method..
	//initially the value of class variables registeredUserName is "no value"
	//then value is set to something by thread 1
	//when thread 2 started it also check the default values of registeredusername which is no more "no value" but it had value set 
	//by thread 1
	
	//what we had observed from above is that two thread shared the class variable "registerusrname" and both work
	//on same reference which leads to data inconsistency
	
	//so we need to make sure the tests are thread safe and data generated by test running from a thread should not 
	//not be used by another test running by another thraed
	

}
